import type { Config } from '../config.ts'

// BestStable preset — auto-generated by layout-maxing-bench.
// // Source: run=#880 verified across 20 seed×example rows
// // Median scores: example-1=~4144, example-4=~8066, example-3=~7883, example-2=~11208
// // Median sum = 31300  (seed omitted — stable across seeds)
export default {
  popSize: 66,
  stop: 1499,
  passes: 1,
  mutationRate: 0.63,
  stagnationThreshold: 71,
  stagnationRate: 1.5,
  diversityBoost: 0.97,
  diversityBoostCap: 3.3,
} satisfies Config
