import type { Config } from '../config.ts'

// BestStableCluster preset — auto-generated by layout-maxing-bench.
// // Source: run=#2004 verified across 5 seeds on example-5
// // Median score: 812028  (seed omitted — stable across seeds)
export default {
  popSize: 35,
  stop: 499,
  generations: 10000,
  passes: 1,
  cluster: 3,
  clusterMax: 12,
  clusterPolishFraction: 0.45,
} satisfies Config
