import type { Config } from '../config.ts'

// BestCluster preset (auto-generated by layout-maxing-bench).
// Sourced from bench run #27 (group="preset", preset="ClusteredNiching").
// example-5 score: 846067 (lower is better).
export default {
  popSize: 40,
  stop: 1499,
  passes: 1,
  tournamentSize: 0.3,
  eliteSize: 4,
  nichingEnabled: true,
  nichingRadius: 0.8,
  nichingExponent: 1.2,
  cluster: 6,
  clusterMax: 12,
  saEnabled: true,
  initialMutation: false,
  seed: 796855095,
} satisfies Config
