import type { Config } from '../config.ts'

// BestClustered preset — auto-generated by layout-maxing-bench.
// // Source: run=#366 group="preset" preset="ClusteredNiching"
// // example-5 score: 457496
export default {
  popSize: 40,
  stop: 1499,
  passes: 1,
  tournamentSize: 0.3,
  eliteSize: 4,
  nichingEnabled: true,
  nichingRadius: 0.8,
  nichingExponent: 1.2,
  cluster: 6,
  clusterMax: 12,
  saEnabled: true,
  initialMutation: false,
  seed: 579293752,
} satisfies Config
