import type { Config } from '../config.ts'

// Best preset (auto-generated by layout-maxing-bench).
// Sourced from bench group="stagnation" sample_seed=115.
// Scores: example-1=3934, example-2=12546, example-3=10161, example-4=10931
// Sum across ex1-4 = 37571 (lower is better).
export default {
  popSize: 18,
  stop: 1499,
  passes: 1,
  mutationRate: 0.933745,
  stagnationThreshold: 28,
  stagnationRate: 1.309038,
  diversityBoost: 0.942149,
  diversityBoostCap: 3.911243,
  seed: 1219732047,
} satisfies Config
