import type { Config } from '../config.ts'

// BestStable preset — auto-generated by layout-maxing-bench.
// // Source: run=#1241 verified across 20 seed×example rows
// // Median scores: example-1=~3934, example-2=~14947, example-3=~10901, example-4=~13723
// // Median sum = 43504  (seed omitted — stable across seeds)
export default {
  popSize: 69,
  stop: 1499,
  passes: 1,
  eliteSize: 7,
  nichingEnabled: true,
  nichingRadius: 0.12,
  nichingExponent: 1.3,
} satisfies Config
