import type { Config } from '../config.ts'

// BestStableCluster preset — auto-generated by layout-maxing-bench.
// // Source: run=#156 verified across 5 seeds on example-5
// // Median score: 1755395  (seed omitted — stable across seeds)
export default {
  stop: 1499,
  passes: 1,
  cluster: 6,
  clusterMax: 15,
} satisfies Config
