import type { Config } from '../config.ts'

// BestClustered preset — auto-generated by layout-maxing-bench.
// // Source: run=#450 group="oat"
// // example-5 score: 617237
export default {
  stop: 1499,
  passes: 1,
  cluster: 6,
  clusterPolishFraction: 0.3,
  seed: 1567673805,
} satisfies Config
