import type { Config } from '../config.ts'

// Best preset — auto-generated by layout-maxing-bench.
// // Source: group="niching" sample_seed=26 run=#1241
// // Single-seed scores: example-1=3934, example-3=10856, example-4=10888, example-2=12260
// // Sum = 37939  (run `deno task verify` then `deno task save-presets` for BestStable)
export default {
  popSize: 69,
  stop: 1499,
  passes: 1,
  eliteSize: 7,
  nichingEnabled: true,
  nichingRadius: 0.12,
  nichingExponent: 1.3,
  seed: 551227529,
} satisfies Config
