import type { Config } from '../config.ts'

// Best preset (auto-generated by layout-maxing-bench).
// Sourced from bench group="stagnation" sample_seed=45.
// Scores: example-1=3934, example-2=11338, example-3=11772, example-4=11230
// Sum across ex1-4 = 38273 (lower is better).
export default {
  popSize: 39,
  stop: 1499,
  passes: 1,
  mutationRate: 0.593827,
  stagnationThreshold: 29,
  stagnationRate: 1.346939,
  diversityBoost: 0.322314,
  diversityBoostCap: 2.668639,
} satisfies Config
